# =============================================================================
# backtest/engine.py — M8: Backtesting Engine
#
# Runs the full strategy on historical data and reports:
#   total return, win rate, max drawdown, Sharpe ratio, profit factor
#
# Usage:
#   python -m backtest.engine --symbol RELIANCE --years 3
#   python -m backtest.engine --all --years 2
# =============================================================================

import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import sqlite3
import pandas as pd
import numpy as np
import json
from datetime import datetime, timedelta
from dataclasses import dataclass, field
from typing import Optional
import yfinance as yf

from config import (
    BACKTEST_START_DATE, BACKTEST_END_DATE, BACKTEST_CAPITAL,
    BACKTEST_RESULTS_DIR, RISK_PER_TRADE_PCT, REWARD_RISK_RATIO,
    RSI_PERIOD, MACD_FAST, MACD_SLOW, MACD_SIGNAL,
    SMA_SHORT, SMA_MID, SMA_LONG, MIN_TA_SCORE, SQLITE_DB_FILE,
    MIN_CONFIDENCE,
)
from analysis.technical_agent import TechnicalAgent
from utils import get_logger

logger = get_logger("Backtest")


@dataclass
class BacktestResult:
    symbol:           str
    start_date:       str
    end_date:         str
    initial_capital:  float
    final_capital:    float
    total_return_pct: float
    total_trades:     int
    wins:             int
    losses:           int
    win_rate_pct:     float
    max_drawdown_pct: float
    sharpe_ratio:     float
    profit_factor:    float
    avg_trade_pnl:    float
    best_trade_pnl:   float
    worst_trade_pnl:  float
    avg_hold_days:    float        = 0.0
    equity_curve:     list        = None   # daily portfolio values
    monthly_returns:  dict        = None   # {"2024-01": 3.5, ...}
    reasoning:        str         = ""     # extra notes (e.g. "replay mode")


class BacktestEngine:
    """
    M8 — Walk-forward backtester using daily OHLCV data.

    Strategy tested:
      - Entry:  TA score >= MIN_TA_SCORE and signal == bullish
      - Exit:   Stop-loss OR take-profit hit (checked daily on high/low)
      - Sizing: 2% risk per trade rule (same as live agent)

    Phase 5 additions:
      - replay_mode: replay historical DB signals instead of regenerating them
      - ablation_config: dict that disables/neutralises specific modules
      - _filter_survivorship_bias(): exclude symbols with < 100 rows of history
    """

    def __init__(self):
        self.ta = TechnicalAgent()
        self.ablation_config: dict = {}
        os.makedirs(BACKTEST_RESULTS_DIR, exist_ok=True)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def run(
        self,
        symbol:         str,
        start_date:     str   = BACKTEST_START_DATE,
        end_date:       str   = BACKTEST_END_DATE,
        capital:        float = BACKTEST_CAPITAL,
        commission_pct: float = 0.0003,   # 0.03% per side (typical NSE brokerage)
        slippage_pct:   float = 0.0005,   # 0.05% slippage on entry/exit
        replay_mode:    bool  = False,    # Phase 5: replay signals from DB
        ablation_config: dict = None,     # Phase 5: module ablation config
    ) -> Optional[BacktestResult]:
        """
        Run backtest for a single symbol.

        replay_mode=True: instead of running TechnicalAgent to generate signals,
          reads saved signals from the SQLite signals table for this symbol and
          date range, then replays them through the same exit logic (SL/TP/expire).
          Returns a BacktestResult with reasoning="replay_mode".

        ablation_config: dict like {"disabled_modules": ["sentiment"]} that
          causes the engine to skip/neutralise specific module contributions
          when building signals.
        """
        if ablation_config is not None:
            self.ablation_config = ablation_config
        else:
            self.ablation_config = {}

        logger.info(
            f"Backtesting {symbol} | {start_date} to {end_date} | capital: {capital:,.0f}"
            + (" | REPLAY MODE" if replay_mode else "")
            + (f" | ablation={ablation_config}" if ablation_config else "")
        )

        df = self._fetch(symbol, start_date, end_date)
        if df is None or len(df) < SMA_LONG + 50:
            logger.warning(f"{symbol}: insufficient history for backtest")
            return None

        if replay_mode:
            trades, equity_curve, dates = self._simulate_replay(
                symbol, df, start_date, end_date, capital, commission_pct, slippage_pct
            )
            result = self._metrics(symbol, start_date, end_date, capital, trades, equity_curve, dates)
            result.reasoning = "replay_mode: signals sourced from DB, not regenerated by TechnicalAgent"
        else:
            trades, equity_curve, dates = self._simulate(df, capital, commission_pct, slippage_pct)
            result = self._metrics(symbol, start_date, end_date, capital, trades, equity_curve, dates)

        if not trades:
            logger.warning(f"{symbol}: no trades generated in backtest period")

        # Phase 5.3: tag each trade with the inferred regime at entry
        trades = self._tag_trades_with_regime(trades, df)
        regime_stats = self.regime_segmented_stats(trades)

        self._save(result, trades)
        self._print(result)
        if regime_stats:
            self._print_regime_stats(regime_stats)
        return result

    def run_all(
        self,
        symbols:         list,
        start_date:      str  = BACKTEST_START_DATE,
        end_date:        str  = BACKTEST_END_DATE,
        delisted_symbols: set = None,     # Phase 5: symbols to exclude (survivorship bias)
        replay_mode:     bool = False,    # Phase 5: replay signals from DB
        ablation_config: dict = None,     # Phase 5: module ablation config
    ) -> pd.DataFrame:
        """
        Run backtest for multiple symbols and return summary DataFrame.

        delisted_symbols: set of symbol strings to exclude from the universe
          before running. Prevents inadvertent survivorship bias when the caller
          already knows which stocks were delisted during the test window.

        Also applies _filter_survivorship_bias() to remove stocks that have
        fewer than 100 rows of price history in the backtest window.
        """
        if delisted_symbols is None:
            delisted_symbols = set()

        # Step 1: remove known-delisted symbols
        pre_count = len(symbols)
        symbols = [s for s in symbols if s not in delisted_symbols]
        dropped = pre_count - len(symbols)
        if dropped:
            logger.info(f"run_all: removed {dropped} delisted symbols from universe")

        # Step 2: survivorship-bias filter (checks actual data availability)
        symbols = self._filter_survivorship_bias(symbols, start_date)

        results = []
        for i, sym in enumerate(symbols, 1):
            logger.info(f"[{i}/{len(symbols)}] {sym}")
            r = self.run(
                sym, start_date, end_date,
                replay_mode=replay_mode,
                ablation_config=ablation_config,
            )
            if r:
                results.append(r)

        if not results:
            return pd.DataFrame()

        df = pd.DataFrame([
            {
                "symbol":           r.symbol,
                "return_%":         r.total_return_pct,
                "trades":           r.total_trades,
                "win_rate_%":       r.win_rate_pct,
                "max_drawdown_%":   r.max_drawdown_pct,
                "sharpe":           r.sharpe_ratio,
                "profit_factor":    r.profit_factor,
            }
            for r in results
        ]).sort_values("return_%", ascending=False)

        # Save summary
        path = os.path.join(BACKTEST_RESULTS_DIR, "summary.csv")
        df.to_csv(path, index=False)
        logger.info(f"Summary saved to {path}")
        self._print_summary(df)

        # Phase 5.3: aggregate regime stats across all symbols
        all_trades = []
        for sym in symbols:
            jpath = os.path.join(BACKTEST_RESULTS_DIR, f"{sym}_backtest.json")
            if os.path.exists(jpath):
                try:
                    with open(jpath) as f:
                        data = json.load(f)
                    all_trades.extend(data.get("trades", []))
                except Exception:
                    pass
        if all_trades:
            regime_stats = self.regime_segmented_stats(all_trades)
            print(f"\n  REGIME-SEGMENTED PERFORMANCE ({len(results)} symbols combined)")
            self._print_regime_stats(regime_stats)
        return df

    # ------------------------------------------------------------------
    # Phase 5 — Survivorship bias filter
    # ------------------------------------------------------------------

    def _filter_survivorship_bias(self, symbols: list, start_date: str) -> list:
        """
        Check each symbol's yfinance history from start_date.
        If a symbol has no data or fewer than 100 rows for that period,
        exclude it with a warning.
        Returns a filtered list with count logged.

        This removes stocks that started trading well after start_date
        (IPOs, relistings) or were delisted before the backtest completed —
        both of which would bias results.
        """
        MIN_ROWS = 100
        passed   = []
        excluded = []

        for sym in symbols:
            try:
                df = yf.Ticker(f"{sym}.NS").history(
                    start=start_date,
                    interval="1d",
                    auto_adjust=True,
                )
                if df is None or df.empty or len(df) < MIN_ROWS:
                    rows = len(df) if df is not None and not df.empty else 0
                    logger.warning(
                        f"Survivorship filter: excluding {sym} — only {rows} rows "
                        f"from {start_date} (minimum {MIN_ROWS})"
                    )
                    excluded.append(sym)
                else:
                    passed.append(sym)
            except Exception as e:
                logger.warning(f"Survivorship filter: excluding {sym} — fetch error: {e}")
                excluded.append(sym)

        logger.info(
            f"Survivorship filter: {len(passed)} passed, {len(excluded)} excluded "
            f"(< {MIN_ROWS} rows or no data) from start_date={start_date}"
        )
        return passed

    # ------------------------------------------------------------------
    # Simulation — standard mode
    # ------------------------------------------------------------------

    def _simulate(
        self, df: pd.DataFrame, capital: float,
        commission_pct: float = 0.0003, slippage_pct: float = 0.0005
    ):
        """
        Walk-forward simulation. For each day:
          1. Calculate TA on data up to that day
          2. If signal is bullish and no open position — enter
          3. Each subsequent day check if SL or TP hit
        Returns (trades, equity_curve, dates).
        """
        trades   = []
        equity   = [capital]
        dates_eq = [str(df.index[SMA_LONG - 1].date())]
        cash     = capital
        position = None   # {entry, sl, tp, qty, entry_date, bars_held}

        disabled = set(self.ablation_config.get("disabled_modules", []))

        for i in range(SMA_LONG, len(df)):
            window = df.iloc[:i]
            today  = df.iloc[i]
            date   = df.index[i]
            # Ensure tz-naive for arithmetic (yfinance may return tz-aware index)
            if hasattr(date, "tzinfo") and date.tzinfo is not None:
                date = date.tz_localize(None)
            cost_factor = 1 + commission_pct + slippage_pct

            # Increment hold counter before exit checks so same-bar exit is impossible
            if position:
                position["bars_held"] = position.get("bars_held", 0) + 1

            # Check exit conditions — only after at least 1 full bar has elapsed
            if position and position["bars_held"] >= 1:
                hi = today["high"]
                lo = today["low"]

                # Stop-loss hit
                if lo <= position["sl"]:
                    exit_px = position["sl"] * (1 - commission_pct - slippage_pct)
                    pnl     = (exit_px - position["entry"]) * position["qty"]
                    cash   += exit_px * position["qty"]
                    hold_d  = (date - pd.Timestamp(position["entry_date"])).days
                    trades.append({
                        "entry_date": position["entry_date"],
                        "exit_date":  str(date.date()),
                        "entry":      position["entry"],
                        "exit":       round(exit_px, 2),
                        "qty":        position["qty"],
                        "pnl":        round(pnl, 2),
                        "exit_type":  "stop_loss",
                        "hold_days":  hold_d,
                    })
                    position = None

                # Take-profit hit
                elif hi >= position["tp"]:
                    exit_px = position["tp"] * (1 - commission_pct - slippage_pct)
                    pnl     = (exit_px - position["entry"]) * position["qty"]
                    cash   += exit_px * position["qty"]
                    hold_d  = (date - pd.Timestamp(position["entry_date"])).days
                    trades.append({
                        "entry_date": position["entry_date"],
                        "exit_date":  str(date.date()),
                        "entry":      position["entry"],
                        "exit":       round(exit_px, 2),
                        "qty":        position["qty"],
                        "pnl":        round(pnl, 2),
                        "exit_type":  "take_profit",
                        "hold_days":  hold_d,
                    })
                    position = None

            # Look for entry (only if no open position)
            if position is None:
                tradeable, bullish, ta_score = self._generate_signal(window, disabled)
                if tradeable and bullish and not self._production_filtered(window, ta_score, date):
                    raw_entry = today["close"]
                    entry     = raw_entry * cost_factor   # include slippage on entry
                    atr       = self._atr(window)
                    sl        = entry - (1.5 * atr)
                    tp        = entry + (REWARD_RISK_RATIO * 1.5 * atr)
                    sl_dist   = entry - sl

                    if sl_dist > 0:
                        risk_amt = cash * RISK_PER_TRADE_PCT
                        qty      = int(risk_amt / sl_dist)
                        cost     = qty * entry

                        if qty > 0 and cost <= cash:
                            cash    -= cost
                            position = {
                                "entry":      round(entry, 2),
                                "sl":         round(sl, 2),
                                "tp":         round(tp, 2),
                                "qty":        qty,
                                "entry_date": str(date.date()),
                                "bars_held":  0,
                            }

            # Mark-to-market equity
            mtm = cash
            if position:
                mtm += today["close"] * position["qty"]
            equity.append(mtm)
            dates_eq.append(str(date.date()))

        # Close any open position at end
        if position:
            last      = df.iloc[-1]["close"]
            exit_px   = last * (1 - commission_pct - slippage_pct)
            pnl       = (exit_px - position["entry"]) * position["qty"]
            cash     += exit_px * position["qty"]
            last_date = df.index[-1]
            if hasattr(last_date, "tzinfo") and last_date.tzinfo is not None:
                last_date = last_date.tz_localize(None)
            hold_d = (last_date - pd.Timestamp(position["entry_date"])).days
            trades.append({
                "entry_date": position["entry_date"],
                "exit_date":  str(df.index[-1].date()),
                "entry":      position["entry"],
                "exit":       round(exit_px, 2),
                "qty":        position["qty"],
                "pnl":        round(pnl, 2),
                "exit_type":  "end_of_period",
                "hold_days":  hold_d,
            })

        return trades, equity, dates_eq

    # ------------------------------------------------------------------
    # Phase 5 — Signal generation with ablation support
    # ------------------------------------------------------------------

    def _production_filtered(self, window: pd.DataFrame, ta_score: float, date) -> bool:
        """
        Mirror the live pipeline's entry filters that are NOT captured by TA alone.
        Returns True if the trade should be skipped (i.e. filtered out).

        Checks applied:
          1. Minimum confidence: TA score / 10 proxies p_direction.
          2. Bear regime abstention: no new longs when price is in a bear regime.
          3. Friday abstention: no new entries on Fridays (mirrors calendar_risk rule).
        """
        if ta_score / 10.0 < MIN_CONFIDENCE:
            return True
        if self._infer_regime(window) == "bear":
            return True
        try:
            if hasattr(date, "dayofweek") and date.dayofweek == 4:
                return True
        except Exception:
            pass
        return False

    def _generate_signal(self, window: pd.DataFrame, disabled: set) -> tuple:
        """
        Generate a (tradeable, bullish, ta_score) signal from the TA agent,
        with ablation overrides applied for any disabled modules.

        disabled is a set of module name strings; when a module is in
        this set its score contribution is zeroed / neutralised so the
        ablation run measures the marginal edge of that module.

        Returns (tradeable: bool, bullish: bool, ta_score: float).
        """
        ta = self.ta.analyse("BT", window)
        if ta is None:
            return False, False, 0.0

        # If no ablation is active, return the raw TA result unchanged.
        if not disabled:
            return ta.tradeable, (ta.signal == "bullish"), ta.score

        # Re-score with disabled modules neutralised.
        # We fetch indicator values from ta.indicators and rebuild score.
        ind = ta.indicators

        score = 0.0

        # 1. RSI (1.5 pts)
        if "momentum_filter" in disabled:
            score += 0.75  # neutral contribution
        else:
            rsi = ind.get("rsi", 50)
            if rsi < 30:
                score += 1.5
            elif rsi < 45:
                score += 1.2
            elif rsi < 55:
                score += 0.75
            elif rsi < 70:
                score += 0.4

        # 2. MACD (1.5 pts) — always kept; no ablation module maps directly
        macd      = ind.get("macd", 0)
        macd_sig  = ind.get("macd_signal", 0)
        macd_hist = ind.get("macd_hist", 0)
        if macd > macd_sig and macd_hist > 0:
            score += 1.2
        elif macd > macd_sig:
            score += 0.75
        else:
            score += 0.2

        # 3. EMA trend (2.0 pts) — partially mapped to multi_timeframe
        if "multi_timeframe" in disabled:
            score += 1.0  # neutral: assume medium trend
        else:
            ema20  = ind.get("ema20",  0)
            ema50  = ind.get("ema50",  0)
            ema200 = ind.get("ema200", 0)
            last   = window["close"].iloc[-1]
            if last > ema20 > ema50 > ema200:
                score += 2.0
            elif last > ema20 and ema20 > ema50:
                score += 1.5
            elif last > ema200:
                score += 1.0
            elif last < ema20 < ema50 < ema200:
                score += 0.0
            else:
                score += 0.5

        # 4. Bollinger Band position (1.0 pts) — mapped to support_resistance
        if "support_resistance" in disabled:
            score += 0.5  # neutral
        else:
            bb_pct = ind.get("bb_pct", 0.5)
            if bb_pct < 0.1:
                score += 1.0
            elif bb_pct < 0.35:
                score += 0.75
            elif bb_pct < 0.65:
                score += 0.5
            elif bb_pct < 0.9:
                score += 0.25

        # 5. Volume breakout (1.5 pts) — mapped to volume_profile
        if "volume_profile" in disabled:
            score += 0.75  # neutral
        else:
            vol_ratio = ind.get("vol_ratio", 1.0)
            if vol_ratio >= 2.5:
                score += 1.5
            elif vol_ratio >= 1.5:
                score += 1.2
            elif vol_ratio >= 1.0:
                score += 0.75
            else:
                score += 0.3

        # 6. ADX trend strength (1.0 pts)
        adx      = ind.get("adx", 20)
        plus_di  = ind.get("plus_di", 0)
        minus_di = ind.get("minus_di", 0)
        if adx >= 25 and plus_di > minus_di:
            score += 1.0
        elif adx >= 25:
            score += 0.0
        elif adx >= 20:
            score += 0.5
        else:
            score += 0.25

        # 7. Stochastic (1.0 pts) — partially mapped to pattern_recognition
        if "pattern_recognition" in disabled:
            score += 0.5  # neutral
        else:
            stoch_k = ind.get("stoch_k", 50)
            stoch_d = ind.get("stoch_d", 50)
            if stoch_k < 20 and stoch_k > stoch_d:
                score += 1.0
            elif stoch_k < 20:
                score += 0.75
            elif stoch_k > 80 and stoch_k < stoch_d:
                score += 0.0
            elif stoch_k > 80:
                score += 0.1
            elif stoch_k > stoch_d:
                score += 0.6
            else:
                score += 0.3

        # 8. OBV (0.5 pts) — neutral when pcr_signal disabled (not a direct match
        # but pcr is a volume-derivative signal)
        if "pcr_signal" in disabled:
            score += 0.25  # neutral
        else:
            obv_bull = ind.get("obv_bullish", False)
            score += 0.5 if obv_bull else 0.0

        # sentiment / fii_dii / earnings_guard are pipeline-level filters;
        # in the backtest context they don't have direct TA score contributions,
        # but we adjust tradeable threshold for them.
        score = round(min(score, 10.0), 2)

        from config import TA_SIGNAL_BULLISH, TA_MIN_TREND_ADX, TA_MAX_BUY_STOCH
        bullish   = score >= TA_SIGNAL_BULLISH
        tradeable = score >= MIN_TA_SCORE and bullish

        # Apply ADX gate unless multi_timeframe is disabled (which encodes trend quality)
        if tradeable and "multi_timeframe" not in disabled:
            if adx < TA_MIN_TREND_ADX:
                tradeable = False

        return tradeable, bullish, score

    # ------------------------------------------------------------------
    # Phase 5 — Replay mode simulation
    # ------------------------------------------------------------------

    def _simulate_replay(
        self,
        symbol:         str,
        df:             pd.DataFrame,
        start_date:     str,
        end_date:       str,
        capital:        float,
        commission_pct: float,
        slippage_pct:   float,
    ):
        """
        Replay signals that were actually generated and stored in the SQLite
        signals table for this symbol and date range.

        Instead of re-running TechnicalAgent, we read the historical BUY signals
        from the DB and replay each one through the same SL/TP/expire exit logic.
        This measures how those real signals actually performed vs the backtest
        model prediction.

        Returns (trades, equity_curve, dates).
        """
        signals = self._load_db_signals(symbol, start_date, end_date)
        if not signals:
            logger.warning(f"{symbol} replay: no signals found in DB for {start_date}–{end_date}")
            return [], [capital], [start_date]

        logger.info(f"{symbol} replay: found {len(signals)} DB signals to replay")

        # Build a date-indexed price lookup for fast access
        price_map: dict = {}
        for idx, row in df.iterrows():
            date_key = str(idx.date()) if hasattr(idx, "date") else str(idx)[:10]
            price_map[date_key] = row

        trades   = []
        equity   = [capital]
        dates_eq = []
        cash     = capital

        # Sort signals by timestamp
        signals.sort(key=lambda s: s["timestamp"])

        # Convert df.index to date strings for ordered iteration
        all_dates = [
            str(d.date()) if hasattr(d, "date") else str(d)[:10]
            for d in df.index
        ]
        # Only process dates within the backtest window
        window_dates = [
            d for d in all_dates
            if start_date <= d <= end_date
        ]

        position = None
        sig_idx  = 0
        sig_dates = {s["timestamp"][:10]: s for s in signals}

        for date_str in window_dates:
            if date_str not in price_map:
                continue
            row = price_map[date_str]
            hi  = row["high"]
            lo  = row["low"]

            # Increment hold counter
            if position:
                position["bars_held"] = position.get("bars_held", 0) + 1

            # Exit checks
            if position and position["bars_held"] >= 1:
                if lo <= position["sl"]:
                    exit_px = position["sl"] * (1 - commission_pct - slippage_pct)
                    pnl     = (exit_px - position["entry"]) * position["qty"]
                    cash   += exit_px * position["qty"]
                    hold_d  = (
                        datetime.fromisoformat(date_str)
                        - datetime.fromisoformat(position["entry_date"])
                    ).days
                    trades.append({
                        "entry_date": position["entry_date"],
                        "exit_date":  date_str,
                        "entry":      position["entry"],
                        "exit":       round(exit_px, 2),
                        "qty":        position["qty"],
                        "pnl":        round(pnl, 2),
                        "exit_type":  "stop_loss",
                        "hold_days":  hold_d,
                        "replay":     True,
                    })
                    position = None

                elif hi >= position["tp"]:
                    exit_px = position["tp"] * (1 - commission_pct - slippage_pct)
                    pnl     = (exit_px - position["entry"]) * position["qty"]
                    cash   += exit_px * position["qty"]
                    hold_d  = (
                        datetime.fromisoformat(date_str)
                        - datetime.fromisoformat(position["entry_date"])
                    ).days
                    trades.append({
                        "entry_date": position["entry_date"],
                        "exit_date":  date_str,
                        "entry":      position["entry"],
                        "exit":       round(exit_px, 2),
                        "qty":        position["qty"],
                        "pnl":        round(pnl, 2),
                        "exit_type":  "take_profit",
                        "hold_days":  hold_d,
                        "replay":     True,
                    })
                    position = None

                # Time-based expiry (same as outcome tracker: 30 days)
                elif position["bars_held"] >= 30:
                    close_px = row["close"]
                    exit_px  = close_px * (1 - commission_pct - slippage_pct)
                    pnl      = (exit_px - position["entry"]) * position["qty"]
                    cash    += exit_px * position["qty"]
                    trades.append({
                        "entry_date": position["entry_date"],
                        "exit_date":  date_str,
                        "entry":      position["entry"],
                        "exit":       round(exit_px, 2),
                        "qty":        position["qty"],
                        "pnl":        round(pnl, 2),
                        "exit_type":  "expired",
                        "hold_days":  position["bars_held"],
                        "replay":     True,
                    })
                    position = None

            # Enter a new position from a DB signal on this date (if no open position)
            if position is None and date_str in sig_dates:
                sig      = sig_dates[date_str]
                entry_px = sig.get("entry_price")
                sl_px    = sig.get("stop_loss")
                tp_px    = sig.get("take_profit")

                # Validate signal fields
                if entry_px and sl_px and tp_px and entry_px > 0:
                    sl_dist = entry_px - sl_px
                    if sl_dist > 0:
                        risk_amt = cash * RISK_PER_TRADE_PCT
                        qty      = int(risk_amt / sl_dist)
                        cost     = qty * entry_px
                        if qty > 0 and cost <= cash:
                            cash    -= cost
                            position = {
                                "entry":      round(entry_px, 2),
                                "sl":         round(sl_px, 2),
                                "tp":         round(tp_px, 2),
                                "qty":        qty,
                                "entry_date": date_str,
                                "bars_held":  0,
                            }

            # Mark-to-market equity
            mtm = cash + (row["close"] * position["qty"] if position else 0)
            equity.append(mtm)
            dates_eq.append(date_str)

        # Close any still-open position at end
        if position and window_dates:
            last_date = window_dates[-1]
            if last_date in price_map:
                close_px = price_map[last_date]["close"]
                exit_px  = close_px * (1 - commission_pct - slippage_pct)
                pnl      = (exit_px - position["entry"]) * position["qty"]
                cash    += exit_px * position["qty"]
                trades.append({
                    "entry_date": position["entry_date"],
                    "exit_date":  last_date,
                    "entry":      position["entry"],
                    "exit":       round(exit_px, 2),
                    "qty":        position["qty"],
                    "pnl":        round(pnl, 2),
                    "exit_type":  "end_of_period",
                    "hold_days":  position["bars_held"],
                    "replay":     True,
                })

        if not dates_eq:
            dates_eq = [start_date]
        if len(equity) == 1:
            pass  # only initial capital; fine

        return trades, equity, dates_eq

    def _load_db_signals(
        self, symbol: str, start_date: str, end_date: str
    ) -> list:
        """
        Load BUY signals for a symbol within a date range from the SQLite DB.
        Returns a list of dicts with keys: timestamp, entry_price, stop_loss,
        take_profit, confidence.
        """
        if not os.path.exists(SQLITE_DB_FILE):
            logger.warning(f"Replay: DB not found at {SQLITE_DB_FILE}")
            return []

        try:
            with sqlite3.connect(SQLITE_DB_FILE) as conn:
                conn.row_factory = sqlite3.Row
                rows = conn.execute("""
                    SELECT timestamp, entry_price, stop_loss, take_profit, confidence
                    FROM signals
                    WHERE symbol   = ?
                      AND action   = 'BUY'
                      AND timestamp >= ?
                      AND timestamp <= ?
                      AND entry_price IS NOT NULL
                      AND stop_loss   IS NOT NULL
                      AND take_profit IS NOT NULL
                    ORDER BY timestamp ASC
                """, (symbol, start_date, end_date + "T23:59:59")).fetchall()
            return [dict(r) for r in rows]
        except Exception as e:
            logger.error(f"Replay: failed to load signals for {symbol}: {e}")
            return []

    # ------------------------------------------------------------------
    # Metrics
    # ------------------------------------------------------------------

    def _metrics(
        self, symbol, start, end, initial, trades, equity, dates
    ) -> BacktestResult:
        final     = equity[-1] if equity else initial
        ret_pct   = ((final - initial) / initial) * 100

        wins      = [t for t in trades if t["pnl"] > 0]
        losses    = [t for t in trades if t["pnl"] <= 0]
        win_rate  = (len(wins) / len(trades) * 100) if trades else 0

        avg_win   = np.mean([t["pnl"] for t in wins])  if wins   else 0
        avg_loss  = np.mean([t["pnl"] for t in losses]) if losses else 0
        pf        = abs(avg_win / avg_loss) if avg_loss != 0 else 0

        all_pnl   = [t["pnl"] for t in trades]
        avg_pnl   = np.mean(all_pnl) if all_pnl else 0
        best      = max(all_pnl)  if all_pnl else 0
        worst     = min(all_pnl)  if all_pnl else 0

        # Average hold duration
        hold_days  = [t.get("hold_days", 0) for t in trades if t.get("hold_days")]
        avg_hold   = np.mean(hold_days) if hold_days else 0

        # Sharpe ratio (annualised, daily returns)
        eq        = pd.Series(equity)
        daily_ret = eq.pct_change().dropna()
        sharpe    = (daily_ret.mean() / daily_ret.std() * np.sqrt(252)
                     if daily_ret.std() > 0 else 0)

        # Max drawdown
        peak  = eq.cummax()
        dd    = ((peak - eq) / peak * 100).max()

        # Monthly returns
        monthly: dict = {}
        if dates and len(dates) == len(equity):
            eq_series  = pd.Series(equity, index=pd.to_datetime(dates))
            monthly_eq = eq_series.resample("ME").last()
            for i in range(1, len(monthly_eq)):
                prev = monthly_eq.iloc[i-1]
                curr = monthly_eq.iloc[i]
                key  = monthly_eq.index[i].strftime("%Y-%m")
                monthly[key] = round((curr - prev) / prev * 100, 2) if prev > 0 else 0.0

        return BacktestResult(
            symbol           = symbol,
            start_date       = start,
            end_date         = end,
            initial_capital  = initial,
            final_capital    = round(final, 2),
            total_return_pct = round(ret_pct, 2),
            total_trades     = len(trades),
            wins             = len(wins),
            losses           = len(losses),
            win_rate_pct     = round(win_rate, 1),
            max_drawdown_pct = round(float(dd), 2),
            sharpe_ratio     = round(float(sharpe), 2),
            profit_factor    = round(pf, 2),
            avg_trade_pnl    = round(avg_pnl, 2),
            best_trade_pnl   = round(best, 2),
            worst_trade_pnl  = round(worst, 2),
            avg_hold_days    = round(float(avg_hold), 1),
            equity_curve     = [round(v, 2) for v in equity],
            monthly_returns  = monthly,
        )

    # ------------------------------------------------------------------
    # Phase 5.3 — Regime-segmented results
    # ------------------------------------------------------------------

    def _infer_regime(self, window: pd.DataFrame) -> str:
        """
        Classify the market environment at the end of a price window.
        Uses SMA200 + SMA50 crossover as a simple proxy for regime detection.
        """
        if len(window) < SMA_LONG:
            return "unknown"
        close  = window["close"]
        sma50  = float(close.rolling(SMA_MID).mean().iloc[-1])
        sma200 = float(close.rolling(SMA_LONG).mean().iloc[-1])
        price  = float(close.iloc[-1])
        pct_from_sma200 = (price - sma200) / sma200

        if price > sma200 and sma50 > sma200:
            return "bull"
        elif price < sma200 and sma50 < sma200:
            return "bear"
        elif abs(pct_from_sma200) < 0.05:
            return "sideways"
        elif price < sma200 and sma50 > sma200:
            return "recovery"
        return "bull"  # default

    def _tag_trades_with_regime(self, trades: list, df: pd.DataFrame) -> list:
        """Add 'regime' key to each trade based on price data at entry date."""
        date_to_idx = {
            str(d.date()) if hasattr(d, "date") else str(d)[:10]: i
            for i, d in enumerate(df.index)
        }
        for trade in trades:
            entry_date = trade.get("entry_date", "")
            idx = date_to_idx.get(entry_date)
            if idx is not None and idx >= SMA_LONG:
                trade["regime"] = self._infer_regime(df.iloc[:idx])
            else:
                trade["regime"] = "unknown"
        return trades

    def regime_segmented_stats(self, trades: list) -> dict:
        """
        Compute win rate, avg PnL, and trade count segmented by regime.
        Returns {regime: {trades, wins, win_rate_pct, avg_pnl, profit_factor}}
        """
        from collections import defaultdict
        buckets: dict = defaultdict(list)
        for t in trades:
            buckets[t.get("regime", "unknown")].append(t)

        result = {}
        for regime, ts in sorted(buckets.items()):
            wins   = [t for t in ts if t["pnl"] > 0]
            losses = [t for t in ts if t["pnl"] <= 0]
            avg_w  = float(np.mean([t["pnl"] for t in wins]))   if wins   else 0.0
            avg_l  = float(np.mean([t["pnl"] for t in losses])) if losses else 0.0
            pf     = round(abs(avg_w / avg_l), 2)               if avg_l  else 0.0
            result[regime] = {
                "trades":        len(ts),
                "wins":          len(wins),
                "win_rate_pct":  round(len(wins) / len(ts) * 100, 1) if ts else 0.0,
                "avg_pnl":       round(float(np.mean([t["pnl"] for t in ts])), 2) if ts else 0.0,
                "profit_factor": pf,
            }
        return result

    def _print_regime_stats(self, stats: dict):
        if not stats:
            return
        print(f"\n  {'REGIME':<12} {'TRADES':>7} {'WIN%':>7} {'AVG PNL':>10} {'PF':>6}")
        print(f"  {'-'*46}")
        for regime, s in stats.items():
            print(f"  {regime:<12} {s['trades']:>7} {s['win_rate_pct']:>6.1f}% "
                  f"Rs.{s['avg_pnl']:>8,.0f} {s['profit_factor']:>6.2f}")

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _fetch(self, symbol: str, start: str, end: str) -> Optional[pd.DataFrame]:
        try:
            df = yf.Ticker(f"{symbol}.NS").history(
                start=start, end=end, interval="1d", auto_adjust=True
            )
            if df.empty:
                return None
            df.columns = [c.lower() for c in df.columns]
            df = df[["open","high","low","close","volume"]]
            df = df[df["close"] > 0].dropna()
            return df.sort_index()
        except Exception as e:
            logger.error(f"Fetch error {symbol}: {e}")
            return None

    def _atr(self, df: pd.DataFrame, period: int = 14) -> float:
        hi, lo, cl = df["high"], df["low"], df["close"]
        tr = pd.concat([hi-lo, (hi-cl.shift()).abs(), (lo-cl.shift()).abs()], axis=1).max(axis=1)
        return float(tr.rolling(period).mean().iloc[-1])

    def get_historical_win_rate(self, symbol: str) -> Optional[float]:
        """
        Returns win_rate_pct from the most recent saved backtest for this symbol.
        Returns None if no backtest result exists yet.
        """
        path = os.path.join(BACKTEST_RESULTS_DIR, f"{symbol}_backtest.json")
        if not os.path.exists(path):
            return None
        try:
            with open(path) as f:
                data = json.load(f)
            return float(data["result"].get("win_rate_pct", 0))
        except Exception:
            return None

    def _save(self, result: BacktestResult, trades: list):
        os.makedirs(BACKTEST_RESULTS_DIR, exist_ok=True)
        path = os.path.join(BACKTEST_RESULTS_DIR, f"{result.symbol}_backtest.json")
        # Don't serialise the full equity curve into JSON — can be large; keep summary only
        result_dict = {k: v for k, v in result.__dict__.items()
                       if k not in ("equity_curve",)}
        with open(path, "w") as f:
            json.dump({"result": result_dict, "trades": trades}, f, indent=2)

    def _print(self, r: BacktestResult):
        print(f"\n{'='*55}")
        print(f"  BACKTEST — {r.symbol}  ({r.start_date} to {r.end_date})")
        if r.reasoning:
            print(f"  NOTE: {r.reasoning}")
        print(f"{'='*55}")
        print(f"  Initial capital  : Rs.{r.initial_capital:>12,.0f}")
        print(f"  Final capital    : Rs.{r.final_capital:>12,.0f}")
        print(f"  Total return     : {r.total_return_pct:>+10.2f}%")
        print(f"  Total trades     : {r.total_trades:>12}")
        print(f"  Win rate         : {r.win_rate_pct:>11.1f}%")
        print(f"  Profit factor    : {r.profit_factor:>12.2f}")
        print(f"  Max drawdown     : {r.max_drawdown_pct:>11.2f}%")
        print(f"  Sharpe ratio     : {r.sharpe_ratio:>12.2f}")
        print(f"  Avg trade P&L    : Rs.{r.avg_trade_pnl:>10,.0f}")
        print(f"  Best trade       : Rs.{r.best_trade_pnl:>10,.0f}")
        print(f"  Worst trade      : Rs.{r.worst_trade_pnl:>10,.0f}")
        print(f"{'='*55}\n")

    def _print_summary(self, df: pd.DataFrame):
        print(f"\n{'='*70}")
        print(f"  BACKTEST SUMMARY — {len(df)} STOCKS")
        print(f"{'='*70}")
        print(df.to_string(index=False))
        print(f"{'='*70}\n")


# =============================================================================
# CLI — python -m backtest.engine
# =============================================================================
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--symbol",  default="RELIANCE", help="NSE symbol")
    parser.add_argument("--years",   type=int, default=3, help="Years of history")
    parser.add_argument("--all",     action="store_true", help="Run all top stocks")
    parser.add_argument("--replay",  action="store_true", help="Replay signals from DB")
    args = parser.parse_args()

    engine = BacktestEngine()
    end   = datetime.today().strftime("%Y-%m-%d")
    start = (datetime.today() - timedelta(days=365 * args.years)).strftime("%Y-%m-%d")

    if args.all:
        symbols = ["RELIANCE","TCS","HDFCBANK","INFY","ICICIBANK",
                   "HINDUNILVR","SBIN","ITC","KOTAKBANK","AXISBANK"]
        engine.run_all(symbols, start, end, replay_mode=args.replay)
    else:
        engine.run(args.symbol, start, end, replay_mode=args.replay)
